version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - postgresData:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$PG_PASSWORD
      - POSTGRES_USER=$PG_USERNAME
      - POSTGRES_DB=postgres

volumes:
  postgresData:
