version: "3.9"
services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - $PG_PORT:$PG_PORT
    environment:
      POSTGRES_USER: $PG_USERNAME
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DATABASE
    volumes:
      - postgresData:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $PG_USERNAME -d $PG_DATABASE
      interval: 1s
      timeout: 5s
      retries: 10

  filmfellow:
    build: ./src
    restart: always
    environment:
      NEXTAUTH_SECRET: generatesecretkey
      DATABASE_URL: $DATABASE_URL
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT

  recommender:
    build: ./src/recommender
    restart: always
    ports:
      - 5000:5000

volumes:
  postgresData:
