name: Pipeline
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: cd src && npm ci && npm run lint && npm run prettier-check
  test-vitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: cp .env.example .env
      - run: docker compose up postgres -d
      - run: cd src && cp .env.example .env && npm ci && npx prisma migrate deploy && npm run prisma:seed
      - run: cd src && npm run test
  test-cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Running cypress tests
        run: |
          cp .env.example .env
          docker compose up postgres recommender -d
          cd src
          cp .env.example .env
          npm ci
          npx prisma migrate deploy
          npm run prisma:seed
          npm run init-admin
          npm run build
          npm run start &
          sleep 1
          npm run cypress:run_headless
  component-test-cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Running cypress tests
        run: |
          cd src
          npm ci
          npm run cypress:component
